config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  devise_for :users
  resources :books do
  	resources :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    member do
     get :following, :followers
    end
  end

  root to: 'home#top'

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	# 1件のpostは複数のlikesを持つ(色々なユーザーが、1件のブログ記事にいいね！ をする)
	has_many :favorites, dependent: :destroy
	# 1件のpostが持つ複数のlikesを介して、複数のusersとつながっている(この記事にいいねした全てのユーザー)[自己結合/自己関連]
	has_many :favorited_users, through: :favorites, source: :user

	has_many :book_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true,length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
  	belongs_to :book
  	validates_uniqueness_of :book_id, scope: :user_id
  	# validates_uniqueness_ofによって、book_idとuser_idの組が1組しかないように

 #  	def favorited_by?(user)
	#   favorites.where(user_id: user.id).exists?
	# end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :following, class_name: "User"
	validates :follower_id, presence: true
 	validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  def favorited_by?(book)
    self.favorites.exists?(book_id: book.id)
  end

  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20}
  validates :name, presence: true, length: { minimum: 2}

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def after_sign_in_path_for(resource)
      if current_user
        flash[:notice] = "Welcome!! You loged in successfully!!" 
        user_path(resource.id)
      else
        flash[:notice] = "Welcome!! You signed up successfully!!" 
        user_path(resource.id)
      end
  end
  
  def after_sign_out_path_for(resource)
        flash[:notice] = "Signed out successfully."
  		  root_path
  end

 end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
	    comment = current_user.book_comments.new(book_comment_params)
	    comment.book_id = book.id
	    comment.save
	    redirect_to book_path(book)
	end

	def destroy
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.find_by(params[:id])
		if comment.user_id == current_user.id
		    comment.destroy
		    redirect_to book_path(book)
		end
	end

	private
	def book_comment_params
	    params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def index
  	@books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
  	if @book.save
      flash[:notice] = "Book was successfully created"
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def show
  	@book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
    flash[:notice] = "Book was successfully updated"
  	redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
    flash[:delete] = "Book was successfully destroyed"
  	redirect_to books_path
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	# いいねを作成する
	def create
      @book = Book.find(params[:book_id])
      @favorite = current_user.favorites.new(book_id: params[:book_id])
      @favorite.save
      redirect_back(fallback_location: root_path)
	end

	# いいねを削除する
	def destroy
	  @book = Book.find(params[:book_id])
	  @favorite = current_user.favorites.find_by(book_id: params[:book_id])
      @favorite.destroy
      redirect_back(fallback_location: root_path)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def about
  end

  def top
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
   def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

  def show
  	@book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user), notice: "userinfo was successfully updated"
    else
      render :edit
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/books/_favorite.html.erb
<% if current_user.favorited_by?(book) %>
  <%= link_to book_favorite_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" style="color: red;">
    <%= book.favorites.count %></i>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="far fa-heart" style="color: black;">
    <%= book.favorites.count %></i>
  <% end %>
<% end %>

app/views/books/_index.html.erb
<h2>User info</h2>
	<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
	    <tbody>
	        <tr>
	          	<th>name</th>
	          	<th><%= user.name %><th>
	        </tr>
	        <tr>
	          	<th>introduction</th>
	          	<th><%= user.introduction %></th>
	        </tr>
	        <%= render 'users/status' %>
	    </tbody>
    </table>

    <div class="row">
       	<% if user.id == current_user.id %>
           	<%= link_to edit_user_path(user) do %>
            	<p class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></p>
           <%end%>
        <% else %>
    		<%= render 'users/follow_form' %>
        <%end%>
    </div>

app/views/books/edit.html.erb
<body>
	<div class="body">
		<div class="container">

	<% if @book.errors.any? %>
		<div id="error_explanation">
    		<h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    		<ul>
    			<% @book.errors.full_messages.each do |msg| %>
       			<li><%= msg %></li>
       			<% end %>
       		</ul>
      	</div>
     <% end %>

			<div class=row>
				<div class="col-md-6 col-md-offset-3">
					<h1>Editing Book</h1>
					<%= form_for(@book) do |f| %>
					 <h4>Title</h4>
					  <%= f.text_field :title, class: "col-xs-12 field" %>
					 <h4>Opinion</h4>
					  <%= f.text_area :body, class: "col-xs-12 field" %><br>
					<%= f.submit'Update Book',class: "btn btn-primary col-xs-12" %>
					<%end%>
					 <%= link_to"Show", book_path(@book.id) %>  
					|
					<%= link_to"Back", books_path %>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/books/index.html.erb
<body>

<div class="body">
<div class="container">

  <% if @book.errors.any? %>
    <div class="alert alert-warning">
      <p>error</p>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


 <%= flash[:notice] %>
 <%= flash[:delete] %>
      <div class="row">
          <div class="col-xs-3">
            <%= render 'books/index', user: @user %>


          	<h2>New book</h2>
          		<%= form_for(@book) do |f| %>
          		<div class="new">Title</div>
          		<%= f.text_field :title, class: "col-xs-12 field" %>
          		<div class="new">Opinion</div>
          		<%= f.text_area :body, class: "col-xs-12 field" %>
            	<p><%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %></p>
          		<% end %>

          </div>

      <div class="col-xs-9">
	    <h2>Books</h2>
	    <table class="table table-hover table-inverse">
		  <thead>
		    <tr>
          <th></th>
		      <th>Title</th>
		      <th>Opinion</th>
          <th></th>
          <th></th>
 		      <th colspan="5"></th>
		    </tr>
		  </thead>

		  <tbody>
		  	<% @books.each do |book| %>
		  	<tr>
		  	 <td><%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg", size: "30x30" %>
         <%end%></td>
		  	 <td><%= link_to book.title, book_path(book.id) %></td>
		  	 <td><%= book.body %></td>

         <td>
            <% if current_user.favorited_by?(book) %>
              <i class="fas fa-heart" style="color: red;"><%= book.favorites.count %></i>
            <% else %>
              <i class="far fa-heart" style="color: black;"><%= book.favorites.count %></i>
            <% end %>
         </td>

         <td>
            <p>
              <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
            </p>
         </td>
        </tr>

		  	<%end%>

		  </tbody>

		</table>
	  </div>
	</div>
</div>
</div>

</body>

app/views/books/show.html.erb
<body>
<div class="body">
<div class="container">

 <%= flash[:notice] %>

    <div class="row">

          <div class="col-xs-3"> 
            <%= render 'books/index', user: @user %>


          	<h2>New book</h2>
          		<%= form_for(@book_new) do |f| %>
          		<div class="new">Title</div>
          		<%= f.text_field :title, class: "col-xs-12 field" %>
          		<div class="new">Opinion</div>
          		<%= f.text_area :body, class: "col-xs-12 field" %>
              <p><%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %></p>
          		<% end %>
          </div>

          <div class="col-xs-9">
			     <h2>Book detail</h2>
			     <table class="table">
		  	 	 <tbody>
		  			<tr>
        			<td><%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg", size: "30x30" %><br>
                <%= link_to @user.name, user_path(@user) %></td>
        			<td><%= link_to @book.title, book_path(@book) %></td>
        			<td><%= @book.body %></td>

              <td>
                <%= render 'books/favorite', book: @book %>
              </td>

              <td><%= @book.book_comments.count %>件コメント</td>

              <% if @user.id == current_user.id %>
            		<td><P class="btn-sm btn-success col-xs-5"><%= link_to "Edit", edit_book_path(@book) %></p></td>
            		<td><p class="btn-sm btn-danger col-xs-5"><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %></p></td>
              <%end%>

    				</tr>
    			 </tbody>
			     </table>

           <h4>コメント一覧</h4>
              <% @book.book_comments.each do |book_comment| %>
                <table class="table">
                  <tbody class="comment">
                    <tr>
                      <td class="col-xs-2">
                        <a href="#"><%= book_comment.user.name %></a>
                        <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
                      </td>
                      <td><div class="comment-entry"><%= book_comment.comment %></div></td>
                      <% if current_user.id == book_comment.user_id %>
                        <td><%= link_to "Delete", book_book_comments_path(book_id: @book), method: :delete %></td>
                      <%end%>
                    </tr>
                  </tbody>
                </table>
              <% end %>



            <%= form_for [@book, @book_comment] do |f| %>
                <div class="row">
                    <div class="col-sm-12">
                        <%= f.text_area :comment, rows:'3', class: "form-control",placeholder: "コメントをここに" %>
                    </div>
                </div>
                <%= f.submit "create comment", class: "btn btn-primary col-xs-12" %>
            <% end %>

          </div>




</div>
</div>
</body>

app/views/home/about.html.erb
<body>
	<div class="body">
		<div class="container">
			<div class="row">
				<div class="top-massage col-md-offset-3 col-md-6">
					<h1>
						welcome to
						<span class="glyphicon glyphicon-book"><strong>Bookers</strong> !!
						</span>
					</h1>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/home/top.html.erb
<body>

	 <%= flash[:notice] %>
	 
	<div class="body">
		<div class="container">
			<p id="notice"></p>
				 <%= flash[:notice] %>
			<div class="row">
				<div class="top-massage col-md-offset-3 col-md-6">
					<h1>
						welcome to
						<span class="glyphicon glyphicon-book"><strong>Bookers</strong> !!
						</span>
					</h1>
					<p>In <span class="glyphicon glyphicon-book"><strong>Bookers</strong>,</span>
					</p>
					<p>you can share and exchange your opinions , inpressions , and emotions</p>
					<p>about various books!</p>
					<div class="btn-wrapper">
					  <div class="row">
					  	<%= link_to new_user_session_path do %>
						<p class="btn btn-info col-xs-10 col-xs-offset-1 sign_in">login</p>
						<%end%><br>
						<%= link_to new_user_registration_path do %>
						<p class="btn btn-success col-xs-10 col-xs-offset-1 sign_up">Sign up</p>
						<%end%>
					  </div>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" rel="stylesheet">
  </head>

  <body>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span class="top">Bookers</span>
      </nav>
      <nav>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to user_path(current_user.id) do %><p class="glyphicon glyphicon-home home"> Home</p><%end%></li>
              <li><%= link_to users_path do %><p class="glyphicon glyphicon-user users"> Users</p><%end%></li>
              <li><%= link_to books_path do %><p class="glyphicon glyphicon-book books"> Books</p><%end%></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %><p class="glyphicon glyphicon-log-out logout"> logout</p><%end%></li>
          </ul>
        <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to root_path do %><p class="glyphicon glyphicon-home home"> Home</p><%end%></li>
              <li><%= link_to home_about_path do %><p class="glyphicon glyphicon-link about"> About</p><%end%></li>
              <li><%= link_to new_user_registration_path do %><p class="glyphicon glyphicon-edit sign-up"> Sign up</p><%end%></li>
              <li><%= link_to new_user_session_path do %><p class="glyphicon glyphicon-log-in sign-in"> login</p><%end%></li>
            </ul>
          <% end %>
      </nav>
    </div>
  </header>

    <%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary col-xs-12" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'users/unfollow' %>
  <% else %>
    <%= render 'users/follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_status.html.erb
<% @user ||= current_user %>
<div class="stats">
  <tr>
    <th>following</th>
    <td>
      <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
          <%= @user.followings.count %>
        </strong>
      </a>
    </td>
  </tr>

  <tr>
    <th>followers</th>
    <td>
      <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
          <%= @user.followers.count %>
        </strong>
      </a>
    </td>
  </tr>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary follow-btn col-xs-12" %>
<% end %>

app/views/users/edit.html.erb
<body>
	<div class="body">
		<div class="container">

	<% if @user.errors.any? %>
	<div id="error_explanation">
    <h2><%= @user.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
       <% end %>
      </div>
      <% end %>

		  <%= flash[:notice] %>
			<div class=row>
				<div class="col-md-6 col-md-offset-3">
					<h1>User info</h1>
					<%= form_for(@user) do |f| %>
					<h5>Name</h5>
						<p><%= f.text_field :name %></p>

					<div class="form-group has-icon">
    					<div class="user-edit-image">
							<h5>Image</h5>
								<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
						</div>
					</div>

					<h5>Introduction</h5>
						<%= f.text_area :introduction %>

					<%= f.submit "Update User" %>

					<%end%>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/users/index.html.erb
<body>

<div class="body">
<div class="container">
 <%= flash[:notice] %>
      <div class="row">
          <div class="col-xs-3">
          	<%= render 'books/index', user: @user %>

          	<h2>New book</h2>
          		<%= form_for(@book) do |f| %>
          		<div class="new">Title</div>
          		<%= f.text_field :title, class: "col-xs-12 field" %>
          		<div class="new">Opinion</div>
          		<%= f.text_area :body, class: "col-xs-12 field" %>
	            <p><%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %></p>
          		<% end %>
          </div>

      <div class="col-xs-9">
	    <h2>Users</h2>

	    <table class="table table-hover table-inverse">
		  <thead>
		    <tr>
 		      <th>image</th>
		      <th>name</th>
		      <th></th>
		      <th></th>
		      <th></th>
		      <th></th>
		      <th colspan="6"></th>
 		    </tr>

		  </thead>

		  <tbody>
		  	<% @users.each do |user| %>
			  	<tr>
				  	<td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg", size:"30x30" %></td>
				  	<td><%= user.name %></td>
				  	<td>フォロワー数：<%= user.followers.count %></td>
				  	<td>フォロー数：<%= user.followings.count %></td>
				  	<td>
				  		<% if user.id != current_user.id %>
					  		<% if current_user.following?(user) %>
						  		<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
									<%= f.submit 'Unfollow' %>
								<% end %>
							<% else %>
								<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
								  	<div><%= f.hidden_field :following_id %></div>
								  	<%= f.submit 'Follow' %>
								<% end %>
							<% end %>
						<% end %>
					</td>
				  	<td><%= link_to "Show", user_path(user.id) %></td>
			  	</tr>
		  	<% end %>
		  </tbody>
		</table>

	  </div>
	</div>
</div>
</div>
</body>

app/views/users/show.html.erb
<body>
<div class="body">
<div class="container">
   <%= flash[:notice] %>
    <div class="row">
      <div class="col-xs-3">
        <%= render 'books/index', user: @user %>


        <h2>New book</h2>
          <%= form_for(@book) do |f| %>
          <div class="new">Title</div>
          <div><%= f.text_field :title, class: "col-xs-12 field" %></div>
          <div class="new">Opinion</div>
          <div><%= f.text_area :body, class: "col-xs-12 field" %></div>
          <div><%= f.submit 'Create Book', class: "btn btn-primary col-xs-12 field" %></div>
          <% end %>
      </div>

          <div class="col-xs-9">
    	    <h2>Books</h2>
    	    <table class="table table-hover table-inverse">
    		  <thead>
    		    <tr>
     		      <th></th>
    		      <th>Title</th>
    		      <th>Opinion</th>
              <th></th>
    		      <th colspan="4"></th>
     		    </tr>
    		  </thead>

    		  <tbody>
    		  	<% @books.each do |book| %>
    		  	<tr>
    		  	<td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:"40x40" %></td>
    		  	<td><%= link_to book.title, book_path(book.id) %></td>
    		  	<td><%= book.body %></td>
            <td><%= book.book_comments.count %>件コメント</td>

    		  	</tr>
    		  	<%end%>
    		  </tbody>
    		</table>

	  </div>
	</div>
</div>
</div>
</body>

app/views/users/show_follow.html.erb
<body>

<div class="body">
<div class="container">

<div class="col-xs-8" >

<h2>Followings</h2>

<div style="text-align: center;">

<% @user.followings.each do |user| %>
	<table class="table table-hover table-inverse">
		<tr>
			<td>ooo</td>
		  <td><%= @user.name %></td>
		  <td><%= link_to '詳細', user_path(user) %></td>
		</tr>
	</table>
<% end %>

</div>

</div>

</div>
</div>

</body>

app/views/users/show_follower.html.erb
<body>

<div class="body">
<div class="container">

<div class="col-xs-8" >

<h2>Followers</h2>

<div style="text-align: center;">

<% @user.followers.each do |user| %>
<table class="table table-hover table-inverse">
<tr>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

</div>

</div>

</div>
</div>

</body>